services:

  database:
    image: postgres:15.1-alpine
    container_name: Database

    volumes:
      - dev_db_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django

    ports:
      - 5432:5432

  server:
    container_name: Server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - "database"
    restart: always
    command: bash /start.sh
    volumes:
      - ./server/:/home/app/webapp/

volumes:
  dev_db_data:
