services:

  server:
    container_name: Server

    build:
      context: .
      dockerfile: ./docker/development/server/Dockerfile

    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development

    env_file:
      - ./env/env.dev.sh

    ports:
      - 8000:8000
    command: bash /start.sh

    volumes:
      - ./server/:/home/app/webapp/

    depends_on:
      - database 

  database:
    container_name: Database
    image: postgres:15.1-alpine

    volumes:
      - dev_db_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django

    ports:
      - 5433:5432

volumes:
  dev_db_data:
